/*=====================================================
SECTION 0: DATABASE SETUP
=====================================================*/

-- Create the project database and switched to it
CREATE DATABASE online_retail_analytics;

USE online_retail_analytics;

-- Create the table to store the cleaned online retail dataset.
CREATE TABLE online_retail (
    Invoice VARCHAR(20),
    StockCode VARCHAR(30),
    Description TEXT,
    Quantity INT,
    InvoiceDate DATETIME,
    Price DOUBLE,
    CustomerID VARCHAR(20),
    Country VARCHAR(100),
    Revenue DOUBLE,
    Month INT,
    Month_Name VARCHAR(20),
    Year INT
);

-- Import the cleaned dataset into the table.
LOAD DATA LOCAL INFILE
"C:/Users/ishan/Desktop/Online Retail Analytics/data/cleaned/online_retail_cleaned.csv"
INTO TABLE online_retail
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(
    Invoice,
    StockCode,
    Description,
    Quantity,
    InvoiceDate,
    Price,
    CustomerID,
    Country,
    Revenue,
    Month,
    Month_Name,
    Year
);

-- Verify the table structure.
DESCRIBE online_retail;

/*=====================================================
SECTION 1: DATA EXPLOARATION
=====================================================*/

-- Query 1: Total Records 
-- Count the total number of transactional records.
SELECT COUNT(*) AS Total_Records FROM online_retail;

-- Query 2 : Unique Customers
-- Count the total number of unique customers.
SELECT COUNT(DISTINCT CustomerID) AS Unique_Customers FROM online_retail;

-- Query 3 : Unique Products
-- Count the total number of unique products.
SELECT COUNT(DISTINCT StockCode) AS Unique_Products FROM online_retail; -- 

-- Query 4 : Number of Countries
-- Count the number of countries where sales were made.
SELECT COUNT(DISTINCT Country) AS Countries FROM online_retail;

-- Query 5 : List of Countries
-- Display all countries present in the dataset.
SELECT DISTINCT Country FROM online_retail ORDER BY Country;

-- Query 6 : Date Range
-- Find the first and last transaction dates.
SELECT MIN(InvoiceDate) AS First_Order, MAX(InvoiceDate) AS Last_Order FROM online_retail;

-- Query 7 : Total Revenue
-- Calculate the total revenue generated.
SELECT SUM(Revenue) AS Total_Revenue FROM online_retail;

-- Query 8 : Average Revenue 
-- Calculate the average revenue generated per transaction line.
SELECT AVG(Revenue) AS Average_Revenue FROM online_retail;

-- Query 9 : Missing Customer IDs
-- Count transaction records with missing Customer IDs.
SELECT COUNT(*) AS Missing_CustomerID FROM online_retail WHERE CustomerID IS NULL OR CustomerID='';

/*=====================================================
Section 2: Sales Analysis
=====================================================*/

-- Query 1 : Monthly Revenue Trend
-- Calculate monthly revenue to analyze sales trends over time.
SELECT Year, Month, Month_Name, SUM(Revenue) AS Monthly_Revenue
FROM online_retail 
GROUP BY Year, Month, Month_Name
ORDER BY Year, Month;

-- Query 2 : Monthly Order Trend
-- Calculate the number of unique orders placed each month.
SELECT Year, Month, Month_Name, COUNT(DISTINCT(Invoice)) AS Total_Orders
FROM online_retail
GROUP BY Year, Month, Month_Name
ORDER BY Year, Month;

-- Query 3 : Top Revenue Products
-- Display the top 10 products generating the highest revenue.
SELECT Description, SUM(Revenue) AS Total_Revenue
FROM online_retail
GROUP BY Description 
ORDER BY Total_Revenue DESC 
LIMIT 10;

-- Query 4 : Top Selling Products
-- Display the top 10 best-selling products by quantity sold.
SELECT StockCode, Description, SUM(Quantity) AS Quantity_Sold
FROM online_retail 
GROUP BY StockCode, Description
ORDER BY Quantity_Sold DESC
LIMIT 10;

-- Query 5 : Average Order Value (AOV)
-- Calculate the average revenue generated per order.
SELECT SUM(Revenue)/COUNT(DISTINCT Invoice) AS Average_Order_Value
FROM online_retail;

-- Query 6 : Top Customers by Revenue
-- Display the top 10 customers generating the highest revenue.
SELECT CustomerID, SUM(Revenue) AS Total_Revenue
FROM online_retail
WHERE CustomerID <> ''
GROUP BY CustomerID
ORDER BY Total_Revenue DESC
LIMIT 10;

-- Query 7 : Average Revenue by Country
-- Calculate the average revenue generated by each country.
SELECT Country, AVG(Revenue) AS Average_Revenue
FROM online_retail
GROUP BY Country 
ORDER BY Average_Revenue DESC;

-- Query 8 : Top Countries by Revenue
-- Display countries ranked by total revenue generated.
SELECT Country, SUM(Revenue) AS Total_Revenue
FROM online_retail
GROUP BY Country
ORDER BY Total_Revenue DESC 
LIMIT 10;

-- Query 9 : Monthly Average Order Value
-- Calculate the average order value for each month.
SELECT Year, Month, Month_Name, SUM(Revenue)/COUNT(DISTINCT Invoice) AS Average_Order_Value
FROM online_retail
GROUP BY Year, Month, Month_Name
ORDER BY Year, Month;

/*=====================================================
Section 3: Customer Analysis
=====================================================*/

-- Query 1 : Top Customers by Orders
-- Display the top 10 customers based on the number of orders placed.
SELECT CustomerID, COUNT(DISTINCT Invoice) AS Total_Orders
FROM online_retail
WHERE CustomerID <> '' 
GROUP BY CustomerID
ORDER BY Total_Orders DESC
LIMIT 10;

-- Query 2 : Customer Performance Report
/*Generate a customer performance report showing total orders,
total revenue, and average order value for each customer.*/
SELECT CustomerID, COUNT(DISTINCT Invoice) AS Total_Orders, SUM(Revenue) AS Total_Revenue,
SUM(Revenue)/COUNT(DISTINCT Invoice) AS Average_Order_Value
FROM online_retail
WHERE CustomerID <> '' 
GROUP BY CustomerID
ORDER BY Total_Revenue DESC;

-- Query 3 : Customer Distribution by Country
-- Display the number of unique customers in each country.
SELECT Country, COUNT(DISTINCT CustomerID) AS Total_Customers
FROM online_retail
WHERE CustomerID <> ''
GROUP BY Country
ORDER BY Total_Customers DESC;

-- Query 4 : VIP Customers
-- Display customers who have generated more than 10,000 in total revenue.
SELECT CustomerID, COUNT(DISTINCT Invoice) AS Total_Orders, SUM(Revenue) AS Total_Revenue
FROM online_retail
WHERE CustomerID <> ''
GROUP BY CustomerID
HAVING SUM(Revenue) > 10000
ORDER BY Total_Revenue DESC;

-- Query 5 : Customer Segmentation (Using CASE)
-- Categorize customers into High, Medium, and Low value segments based on total revenue.
SELECT CustomerID, SUM(Revenue) AS Total_Revenue,
CASE 
	WHEN SUM(Revenue) >= 10000 THEN 'High Value'
    WHEN SUM(Revenue) >= 5000 THEN 'Medium Value'
    ELSE 'Low Value'
END AS Customer_Segment 
FROM online_retail
WHERE CustomerID <> ''
GROUP BY CustomerID
ORDER BY Total_Revenue DESC;

-- Query 6 : Customer Performance Dashboard
/*Generate a customer performance dashboard showing total orders, total revenue, 
average order value, and average items per order for each customer.*/
SELECT CustomerID, COUNT(DISTINCT Invoice) AS Total_Orders,
SUM(Revenue) AS Total_Revenue, SUM(Revenue)/COUNT(DISTINCT Invoice) AS Average_Order_Value,
SUM(Quantity)/COUNT(DISTINCT Invoice) AS Average_Items_Per_Order
FROM online_retail
WHERE CustomerID <> ''
GROUP BY CustomerID
ORDER BY Total_Revenue DESC;

/*=====================================================
Section 4: Country Analysis
=====================================================*/

-- Query 1 : Country Performance Report
/* Generate a country performance report showing:
Total customers, Total revenue , Average order value */
SELECT Country, COUNT(DISTINCT CustomerID) AS Total_Customers,
COUNT(DISTINCT Invoice) AS Total_Orders, SUM(Revenue) AS Total_Revenue,
SUM(Revenue)/COUNT(DISTINCT Invoice) AS Average_Order_Value,
SUM(Revenue)/COUNT(DISTINCT CustomerID) AS Revenue_Per_Customer
FROM online_retail
WHERE CustomerID <> ''
GROUP BY Country
ORDER BY Total_Revenue DESC;

-- Query 2 : Revenue Contribution by Country
-- Calculate the percentage contribution of each country to the total revenue.
SELECT Country,
SUM(Revenue) AS Total_Revenue,
SUM(Revenue)/
(
	SELECT SUM(Revenue)
    FROM online_retail
    WHERE CustomerID <> ''
) * 100 AS Revenue_Contribution_Percentage
FROM online_retail
WHERE CustomerID <> ''
GROUP BY Country
ORDER BY Total_Revenue DESC;

-- Query 2 : Countries Above Average Revenue
-- Display countries whose total revenue is above the average revenue generated across all countries.
SELECT Country, 
SUM(Revenue) AS Total_Revenue
FROM online_retail
WHERE CustomerID <> ''
GROUP BY Country
HAVING SUM(Revenue)>
(
	SELECT AVG(Country_Revenue)
    FROM
    (
		SELECT SUM(Revenue) AS Country_Revenue
        FROM online_retail
        WHERE CustomerID <> ''
        GROUP BY Country
	)	AS Revenue_Table 
) 
ORDER BY Total_Revenue DESC;

/*=====================================================
Section 5: Time-Series Analysis
=====================================================*/

-- Query 1 : Revenue by Quarter
-- Calculate the total revenue generated in each quarter.
SELECT Year, QUARTER(InvoiceDate) AS Quarter, SUM(Revenue) AS Total_Revenue
FROM online_retail
GROUP BY Year, QUARTER(InvoiceDate)
ORDER BY Year, Quarter;

-- Query 2 : Revenue by Calendar Month
-- Calculate the total revenue generated in each calendar month.
SELECT Month, Month_Name, SUM(Revenue) AS Total_Revenue
FROM online_retail
GROUP BY Month, Month_Name
ORDER BY Total_Revenue DESC;

-- Query 3 : Monthly Revenue Trend
-- Display the monthly revenue trend in chronological order.
SELECT Year, Month, Month_Name, SUM(Revenue) AS Total_Revenue
FROM online_retail
GROUP BY Year, Month, Month_Name
ORDER BY Year, Month;

/*=====================================================
Section 6: Advanced SQL
=====================================================*/

-- Query 1 : Customers Above Average Revenue 
-- Display customers whose total revenue is above the average customer revenue.
WITH Customer_Summary AS 
(
	SELECT CustomerID, SUM(Revenue) AS Total_Revenue
    FROM online_retail
    WHERE CustomerID <> ''
    GROUP BY CustomerID
)
SELECT CustomerID, Total_Revenue
FROM Customer_Summary
WHERE Total_Revenue> (SELECT AVG(Total_Revenue) FROM Customer_Summary)
ORDER BY Total_Revenue DESC;

-- Query 2 : Customer Ranking Using ROW_NUMBER()
-- Assign a unique rank to each customer based on total revenue.
WITH Customer_Summary AS 
(
	SELECT CustomerID, SUM(Revenue) AS Total_Revenue
    FROM online_retail
    WHERE CustomerID <> ''
    GROUP BY CustomerID
)
SELECT ROW_NUMBER() OVER (ORDER BY Total_Revenue DESC) AS Customer_Rank, CustomerID, Total_Revenue
FROM Customer_Summary;

-- Query 3 : Customer Ranking Using RANK()
-- Assign the same rank to customers with equal revenue. The next rank is skipped when a tie occurs.
WITH Customer_Summary AS 
(
	SELECT CustomerID, SUM(Revenue) AS Total_Revenue
    FROM online_retail
    WHERE CustomerID <> ''
    GROUP BY CustomerID
)
SELECT RANK() OVER (ORDER BY Total_Revenue DESC) AS Customer_Rank, CustomerID, Total_Revenue
FROM Customer_Summary;

-- Query 4 : Customer Ranking Using DENSE_RANK()
-- Assign the same rank to customers with equal revenue without skipping rank numbers.
WITH Customer_Summary AS
(
	SELECT CustomerID, SUM(Revenue) AS Total_Revenue
    FROM online_retail
    WHERE CustomerID <> ''
    GROUP BY CustomerID
)
SELECT DENSE_RANK() OVER (ORDER BY Total_Revenue DESC) AS Customer_Rank, CustomerID, Total_Revenue
FROM Customer_Summary;

-- Query 5 : Customer Ranking Within Each Country
-- Rank customers by total revenue within each country.
WITH Customer_Summary AS
(
	SELECT Country, CustomerID, SUM(Revenue) AS Total_Revenue
    FROM online_retail
    WHERE CustomerID <> ''
    GROUP BY Country, CustomerID
)
SELECT Country, CustomerID, Total_Revenue, 
DENSE_RANK() OVER (PARTITION BY Country ORDER BY Total_Revenue DESC) AS Customer_Rank 
FROM Customer_Summary
ORDER BY Country, Customer_Rank;

-- Query 6 : Previous Month Revenue Using LAG()
-- Display monthly revenue along with the previous month's revenue.
WITH Monthly_Revenue AS 
(
	SELECT Year, Month, Month_Name, SUM(Revenue) AS Total_Revenue
    FROM online_retail
    GROUP BY Year, Month, Month_Name
)
SELECT Year, Month, Month_Name, Total_Revenue,
LAG(Total_Revenue) OVER (ORDER BY Year, Month) AS Previous_Month_Revenue
FROM Monthly_Revenue;

-- Query 7 : Month-over-Month Revenue Growth
-- Calculate the month-over-month revenue growth percentage.
WITH Monthly_Revenue AS 
(
	SELECT Year, Month, Month_Name, SUM(Revenue) AS Total_Revenue
    FROM online_retail
    GROUP BY Year, Month, Month_Name
),
Revenue_Comparision AS 
(
	SELECT Year, Month, Month_Name, Total_Revenue,
    LAG(Total_Revenue) OVER (ORDER BY Year, Month) AS Previous_Month_Revenue
    FROM Monthly_Revenue
)
SELECT Year, Month, Month_Name, Total_Revenue, Previous_Month_Revenue,
((Total_Revenue - Previous_Month_Revenue)/Previous_Month_Revenue) *100 AS MoM_Growth_Percentage
FROM Revenue_Comparision;

-- Query 8 : Running Total Revenue
-- Calculate the cumulative revenue over time.
WITH Monthly_Revenue AS
(
	SELECT Year, Month, Month_Name, SUM(Revenue) AS Total_Revenue
    FROM online_retail 
    GROUP BY Year, Month, Month_Name
)
SELECT Year, Month, Month_Name, Total_Revenue,
SUM(Total_Revenue) OVER (ORDER BY Year, Month) AS Running_Total_Revenue
FROM Monthly_Revenue;

-- Query 9 : Top Product in Each Country
-- Display the highest revenue-generating product in each country.
WITH Product_Revenue AS 
(
	SELECT Country, StockCode, Description, SUM(Revenue) AS Total_Revenue
    FROM online_retail
    GROUP BY Country, StockCode, Description
),
Ranked_Products AS 
(
	SELECT Country, StockCode, Description, Total_Revenue,
    ROW_NUMBER() OVER (PARTITION BY Country ORDER BY Total_Revenue DESC) AS Product_Rank
    FROM Product_Revenue
)
SELECT Country, StockCode, Description, Total_Revenue
FROM Ranked_Products
WHERE Product_Rank=1
ORDER BY Country;

-- Query 10 : Top Customer in Each Country
-- Display the highest revenue-generating customer in each country.
WITH Customer_Revenue AS 
(
	SELECT Country, CustomerID, SUM(Revenue) AS Total_Revenue
    FROM online_retail
    WHERE CustomerID <> ''
    GROUP BY Country, CustomerID 
),
Ranked_Customers AS 
(
	SELECT Country, CustomerID, Total_Revenue, 
    ROW_NUMBER() OVER (PARTITION BY Country ORDER BY Total_Revenue DESC) AS Customer_Rank
    FROM Customer_Revenue
)
SELECT Country, CustomerID, Total_Revenue 
FROM Ranked_Customers
WHERE Customer_Rank=1 
ORDER BY Country;

/*=====================================================
BUSINESS INSIGHTS
=====================================================*/

/* Insight 1 : The United Kingdom generated the highest total revenue, 
making it the company's largest market.*/

/* Insight 2 : November consistently recorded the highest monthly revenue
across both 2010 and 2011, with November 2011 generating 1,503,866.78 in revenue.
This suggests strong seasonal demand during the holiday shopping period.*/

/* Insight 3 : The United Kingdom contributed 82.82% of the total revenue,
making it the company's dominant market. This indicates a high dependence on a single country, 
while other international markets contribute a relatively small share of overall revenue.*/

/* Insight 4 : A relatively small group of high-value customers contributes 
a significant share of the total revenue. 
Customer 18102 generated the highest revenue (580,987.04), 
highlighting the importance of retaining key customers.*/

/* Insight 5 : Internation Presence of the company is good, with it haveing customers in 43 countries.*/

/* Insight 6 : The United Kingdom has the largest customer base with 5,350 unique customers,
significantly exceeding all other countries. This indicates a strong market presence and a
high concentration of customers in the UK.*/

/* Insight 7 : Revenue shows a clear seasonal trend, with the fourth quarter
(Q4) consistently generating the highest revenue in both 2010 and 2011. 
This suggests increased customer demand during the holiday shopping season.*/
